Feat/#27
TeamCommerce/backend-server pull request #28
Opened 2023-08-12 13:02 UTC by h-beeen

## Issue ticket link and number
- #27 

## Describe changes
- 펫 엔티티에 대한 기본 도메인 로직의 기반을 잡았습니다.
```sql
    create table t_product (
        inventory int unsigned,
        origin_price int unsigned,
        created_date datetime default CURRENT_TIMESTAMP not null,
        product_id bigint not null auto_increment,
        promotion_id bigint,
        updated_date datetime default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP not null,
        brand enum ('ADADIS','IUP_STUDIO'),
        description varchar(100),
        name varchar(100),
        status enum ('AVAILABLE_FOR_ORDER','DISABLED','OUT_OF_STOCK'),
        primary key (product_id)
    )
```

- 자세한 제약조건은 위 쿼리문을 확인해주세요.

2023-08-12 13:51 UTC, EunChanNam requested changes
전체적으로RequiredArgumentCostructor 를 임베디드 타입에 사용하셨는데 해당 어노테이션은 final 키워드가 없는 속성에는 작동하지 않아요. 
그래서 제거하고 의미있는 생성자를 private 로 선언하거나 AllArgumentConstructor 를 private 으로 활용해서 스태틱 메소드를 이용해도 될거같아요.
아니면 AllArgumentConstructor 를 그냥 public 으로 사용해도 괜찮을거같네요.

2023-08-12 13:51 UTC, EunChanNam commented on src/test/java/com/commerce/backendserver/member/presentation/MemberControllerTest.java
> +@ActiveProfiles("test")
해당 어노테이션 안다는 방향으로 수정한거로 기억하는데 아닌가요?

2023-08-12 13:51 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private Promotion promotion;
해당 부분은 가격이라는 공통 관심사니까 Price 혹은 다른 네이밍으로 임베디드 타입으로 묶는게 어떨까요?

2023-08-12 13:51 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
프로모션은 프로모션마다의 고유의 특성이 있다고 생각해요. 그래서 프로모션 마다의 이름이 존재하면 좋을거같아요.
예를들면 DEFUALT_PROMOTION 이렇게 그리고 할인율이란건 결국 프로모션의 고유의 값이니까 PromotionAttribute 이렇게 enum 을 정의해서 그 안에 프로모션 이름, 프로모션 할인율(discoutAmount)를 정의하면 좋을거같은데 이부분 어떤지 생각해보시고 말씀주시면 좋을거같아요.

2023-08-12 13:51 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
> +    @NotNull
해당 어노테이션 엔티티 레벨에서도 작동하나요? 보통 엔티티에서 제약조건은 Colum 어노테이션으로 정의했는데 궁금해서 코멘트 넣습니다.

2023-08-12 15:32 UTC, EunChanNam requested changes

2023-08-12 15:32 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private Promotion promotion;
한 프로모션이 여러 상품에 적용될 수 있으니 ManyToOne 이 맞는거같아요.

2023-08-12 19:15 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private Promotion promotion;
이 부분에 대해서 명확하게 기준을 잡고 가면 좋을 것 같아요.
제가 생각했던 프로모션에 대한 로직은 이거였어요.

- 정가
- 정률/정액할인 타입
- DiscountedValue
- 판매가

해당 프로모션은 단수로만 적용할 수 있으며, 
이 외적인 부분은 `Coupon` 이라는 엔티티를 통해서 설계하는게 맞다고 생각했어요.

여기서 정의하고 싶었던 `Promotion` 은 어드민 계정으로 신규 상품 등록/정가 수정/할인가 수정 등의 기능을 수행할 때
단일 값으로 선택하는 프로모션이 조금 더 적절한 프로모션 적용이라고 생각합니다.

<img width="260" alt="스크린샷 2023-08-13 오전 4 12 23" src="https://github.com/TeamCommerce/backend-server/assets/112257466/1e78645d-900c-4647-9d25-2059c2f4116e">

만약 여기서 유저가 `1000원 정액 할인 쿠폰`과 `10% 정률 할인 쿠폰`을 사용한다고 가정 했을 때, 
단일 `Promotion(관리자가 지정한 상품 default 프로모션` 이 적용된 `판매가` 에서 다중쿠폰 사용을 허용한다면, `Coupon(사용자가 선택권을 지니는 프로모션)`이 `@ManyToOne` 사용으로 매핑하는게 더 적절한 설계라고 생각합니다.

어떻게 생각하시는지 궁금합니다! @EunChanNam

2023-08-12 19:21 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
> +    @NotNull
추후 해당 컬럼에 대한 검증 메소드를 구현하여,
생성자를 통해, 객체를 생성할 때, 검증이 되지 않은 파라미터(예를 들면 정률 할인 -20%)는 예외를 던지게 구성할 예정입니다.
다만 비즈니스 로직에서 "정말 예기치 못한 오류가 발생해" 검증 메소드를 통과한다고 하더라도, 엔티티 자체에 Constraint를 적용해, 음수 파라미터에 대한 제약을 완벽하게 할 수 있다고 판단했습니다.

실제로 `@Column(columnDefinition = "int unsigned")` 로 지정된 컬럼에 음수값을 삽입할 경우, SQL Error가 발생해, 예외를 던지게 됩니다.

<img width="463" alt="스크린샷 2023-08-13 오전 4 21 00" src="https://github.com/TeamCommerce/backend-server/assets/112257466/2b51c62f-9a7f-4e53-bd22-b2020f0c07c6">

- 파라미터에 대한 검증 (메소드-엔티티 레벨)
- 데이터 베이스 컬럼 자체에 대한 제약조건 (DB 레벨)

2023-08-12 19:22 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private Promotion promotion;
이 부분은 공통 관심사로 묶는 판단이 적절해 보여요!
프로모션을 매핑하는 부분만 신경쓰다보니, 
두 객체의 공통 관심사는 조금 신경을 못 썼던 것 같아요 ㅎ

이 부분은 코드리뷰 주신 내용대로 수정해 보겠습니다!

2023-08-12 19:23 UTC, h-beeen commented on src/test/java/com/commerce/backendserver/member/presentation/MemberControllerTest.java
> +@ActiveProfiles("test")
이 부분은 같이 `Tab Indent` 를 통일하는 과정에서,
커밋이 조금 꼬였는지 왜 갑자기 등장했는지 모르겠네요..?

삭제하도록 하겠습니다!

2023-08-12 19:25 UTC, h-beeen commented
> 전체적으로RequiredArgumentCostructor 를 임베디드 타입에 사용하셨는데 해당 어노테이션은 final 키워드가 없는 속성에는 작동하지 않아요. 그래서 제거하고 의미있는 생성자를 private 로 선언하거나 AllArgumentConstructor 를 private 으로 활용해서 스태틱 메소드를 이용해도 될거같아요. 아니면 AllArgumentConstructor 를 그냥 public 으로 사용해도 괜찮을거같네요.

아직 생성자에 대한 구체적인 틀을 짜지 않은 상태지만 꼼꼼하게 리뷰해 주셔서 감사드립니다.

`@RequiredArgsConstructor` 어노테이션이 final이 아닌 상황에서 작동하지 않는다는 점은 오늘 처음 알고갑니다! 좋은 정보 감사드립니다.

생성자에 대한 구체적인 내용은, 이번 코드리뷰 수정 커밋으로 조금 더 구체적으로 구현해서, PR 날리도록 하겠습니다. 생성자 및 서식지정자 해당 부분에 대해서 꼼꼼하게 검토해주시면, 더 좋은 코드로 함께할 수 있을 것 같아요!! 몇몇 부분에 대해서는 저랑 상이한 의견이 있는 것 같아, 해당 부분에 코멘트 달아 두었습니다! 확인 후 리뷰 부탁드려요 :) 감사합니다! Shout out to @EunChanNam

2023-08-13 00:04 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
> +    @NotNull
아 저는 NotNull 어노테이션에 대해서 질문드렸던겁니다만 성실한 답변 감사합니다. 해당부분은 제가 직접 찾아볼게요.

2023-08-13 00:14 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private Promotion promotion;
제가 강조하는 부분을 좀 더 쉽게 설명해드릴게요.
- 프로모션은 단순 할인율을 넘어 프로모션 자체에 의미가 있음
- 사진의 예를 이용하면 20% 할일인 적용되는데 이를 '슈퍼 할인 프로모션' 이라고 하면 해당 프로모션은 해당 상품을 위해 존재하는 프로모션이 아니라 여러 상품에 적용될 수 있는 프로모션임
- 그래서 한 프로모션에 여러 상품을 적용할 수 있는 ManyToOne이 적합해보임.
- 쿠폰은 프로모션과 별개로 작용한다. 이부분도 당연히 ManyToOne 이 적절한.

2023-08-13 00:47 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
@h-beeen 해당 부분에 대해서도 한번 의견 부탁드레요 😊

2023-08-13 13:29 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
이건 체크창에 보이지 않았던 의견인데 지금 확인했어요!
이걸 봤으면 아래 질문을 안달았을 것 같은데 ㅎㅅㅎ
프로모션별 프로모션 할인율로 리팩토링 해보겠습니다!

2023-08-16 06:40 UTC, EunChanNam approved these changes
다음 작업에 이어서 하시죠.

2023-08-16 08:34 UTC, merged