feat: Add Constructor / Validation Method for Product Entity
TeamCommerce/backend-server pull request #40
Opened 2023-08-19 15:42 UTC by h-beeen

## Issue ticket link and number
- #39 

## Describe changes
- Product 도메인에서 누락되었던 Image 컬럼을 추가합니다.
- Product 및 하위 도메인의 Constructor과 기본 Validation 로직을 추가합니다.
- 상기 작업사항 외 내용 푸쉬는 추후 개발내용입니다.

2023-08-19 15:44 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/image/domain/Image.java
> +    /* static factory method */
같이 정한 컨벤션과 다른 양식으로 적어버렸네요.
코드리뷰 받고, 수정사항 있으면 같이 수정하겠습니다.

2023-08-20 01:21 UTC, EunChanNam requested changes

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    public static Product Of(
생성메서드 이름을 엔티티 만큼은 의미있는 네이밍 부탁드립니다.

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    }
위에 리뷰에서 말씀드린 것과 비슷하게 이런 임베디드 타입에 대한 검증은 이렇게 단순히 null 체크가 아니라 **임베디드 타입 안에서 검증**이 필요할거같아요.

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +        validateOptions(options);
현재 단계에서 이런 empty 체크, null 체크 의미가 있나 싶네요. 
이런 값을 채우는 부분에서 검증이필요하다고 생각합니다.
예를 들면 이미지를 추가하는 단계나 다른 속성의 값을 채우는 단계 정도 있겠네요.

그래서 현재 검증로직은 모두 없애고 필요한것만 새롭게 구성하는게 좋을거같아요.

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/ProductImage.java
> +    @AttributeOverride(name = "path", column = @Column(name = "product_image_path", columnDefinition = "varchar(200)"))
임베디드 타입 안에서 정의하는게 깔끔할거같아요.

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
> +        validateDescription(description);
이러한 속성들에 대한 null 체크, empty 체크 Request 레벨에서 진행하는데 의미가 있나싶네요.
제약조건으로 최종 방어막만 유지하는게 나을거같아요.

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
> +    }
마찬가지로 null 체크는 Request 레벨에서 다진행될거고 솔직히 originPrice 에 대한 검증정도만 남기는게 어떨까요

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java
> +    public static ProductBrand fromString(String input) {
fromString 보다 더 의미있는 메소드 이름이 좋을거같아요.
예를 들면 `matchBrand` 이런 느낌으로

2023-08-20 01:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java
> +        return brand.get();
findFirst 하고
orElseThrow 로 연결 후에 리턴하는게 더 깔끔할거같네요

2023-08-20 01:59 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/image/domain/Image.java
> +    private String path;
이미지 패키지 구조 설계를 다음과 같이 진행했습니다.

URL은 추후 S3나 NCP의 업로드 서비스를 이용해 얻은 순수 이미지 URL 이미지, 파일 경로를 포함한 이름의 변수로 활용할 수 있을 것 같습니다.

아직 이미지 도메인 설계가 되지 않아 가상의 변수명인 만큼, 너무 무게 있게 변수명에 대해서 고민하지 않고 지은 부분이라, 추후 도메인 설계 과정에서 수정해도 좋을 것 같아요.

2023-08-20 02:01 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/image/domain/Image.java
> +    public void validatePath(final String path) {
앗 이 부분은 접근지정자를 잘못 정의했네요!
잘 캐치해주신 것 같아요! 감사합니다!

2023-08-20 02:04 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
> +@Transactional(readOnly = true)
CRUD에서 R을 담당하는 FindService의 트랜잭션을 상기와 같이 readOnly = true로 정의했습니다.
해당 서비스 클래스 안에는 찾는 비즈니스 로직(반드시 Repository Layer를 거치는)이 포함될 예정으로 설계했기에 위와 같이 진행했습니다.
해당 클래스는 모든 메소드에 `@Transactional(readOnly = true)` 이 붙을 예정인데 어떤 이유로 분리가 필요하다고 판단하셨는지 궁금해요.

2023-08-20 02:24 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/ProductRegisterService.java
> +public class ProductRegisterService {
이부분은 좋은 것 같아요!
다만 비즈니스 로직이 복잡해질 엔티티가 분명해서, C / U / D를 조금 직관적으로 분리해보고자 그렇게 설계했어요.
CRUD를 엄격하게 분리하는 것이 작은 로직에서 보면 의미가 없는 일 일지라도,
Product는 우리 서비스에서 가장 비중있는 엔티티이기 때문에, 서비스 로직의 분리를 어떻게 가져갈지에 대해서 아직도 고민이 많아요.
ProductService로만 CUD를 구현하게 된다면, 너무 비즈니스 로직이 이곳에 쏠리지 않을까 우려됩니다.

서비스 로직 분리에 대해서 어떻게 생각하시는지 조금 더 자세히 알고싶어요!

2023-08-20 02:26 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/ProductImage.java
> +    @AttributeOverride(name = "path", column = @Column(name = "product_image_path", columnDefinition = "varchar(200)"))
여기서 Image는 ProductImage, ReviewImage, UserProfileImage..등등 임베디드 타입의 재사용성을 고려하여 설계되었습니다.
이미지 임베디블 타입 안에서 해당 컬럼의 이름을 정의하게 된다면, 재사용에 제한이 생기게 되어, `@AttributeOverride` 형식으로 설계하였습니다.

Embedded 타입 자체가 재사용성과 값 타입의 객체화가 목적을 갖고 사용한다고 알고 있습니다.
이 부분에 대해서도 어떻게 생각하시는지 더 알고 싶어요!
리뷰 부탁드립니다 :)

2023-08-20 02:38 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/image/domain/Image.java
> +    private String path;
그러면 path 는 제거해도 될거같네요

2023-08-20 02:40 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
> +        validateDescription(description);
Dto 클래스는 앞으로 무수히 많이 생겨나게 될 거에요.
우리가 많은 Dto 클래스를 만들더라도, 모든 Dto를 관통하는 메인 생성자 자체에 검증 로직이 있다면,
가령 ReqDto가 잘못 설계되더라도, 클라이언트가 예상치 못한 SQL-Error를 받진 않을 것이라는 생각이 듭니다.

극단적으로 Request Level에서의 테스트를 진행하지 않는다고 하더라도, 
도메인 로직에서 첨예하게 짜여진 검증 로직이 있고, 이를 바탕으로 우리가 설계한 전역 에러를 던질 수 있다면
이것이 조금 더 안정적인 설계 방법이라고 개인적으로 생각합니다!
조금 더 DDD에 적합한 방법이라는 생각이 들기도 하구요!

오히려 저는 반대로, 도메인 로직에서의 최대 검증 / reqDto 수준에서의 최종 방어막 검증이
우리가 추구하는 DDD에 조금 더 적합하다는 판단도 듭니다.

은찬님의 생각은 어떠신가요? 궁금합니다!

2023-08-20 02:41 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
> +    }
상기 답변 참고 부탁드립니다.

2023-08-28 15:10 UTC, EunChanNam approved these changes

2023-08-28 15:13 UTC, merged