feat: Add
TeamCommerce/backend-server pull request #58
Opened 2023-09-07 10:07 UTC by h-beeen

## Issue ticket link and number
- #49

---

## Describe changes

### 단일 상품 조회 API

- Request Header
```json
GET /api/products/{productId}
Host : localhost:8080
Authorization : Bearer ${ACCESS_TOKEN}
Content-type : application/json
```

- Request Body
```json
```

- Response Body
```json
{
    "id": 1,
    "originPrice": 179000,
    "promotionType": "FIX_DISCOUNT",
    "promotionValue": 50000,
    "promotionDiscountedAmount": 50000,
    "appliedPromotionPrice": 129000,
    "images": [
        "https://github.com/h-beeen/h-beeen/assets/112257466/9fad436d-393f-4730-87ac-f153fbb41ebd",
        "https://github.com/h-beeen/h-beeen/assets/112257466/16c2df83-5c1c-406b-83f4-bb5c0d4310c6"
    ],
    "options": [
        {
            "optionId": 1,
            "color": {
                "colorCode": "#FFFFFF",
                "korColorName": "매트 화이트",
                "engColorName": "Matt White"
            },
            "selectionOption": {
                "size": "TWO_XL",
                "optionType": "쭈리",
                "optionValue": "TRUE",
                "additionalFee": 300
            },
            "inventory": 300,
            "productStatus": "AVAILABLE"
        },
        {
            "optionId": 2,
            "color": {
                "colorCode": "#FFFFFF",
                "korColorName": "매트 화이트",
                "engColorName": "Matt White"
            },
            "selectionOption": {
                "size": "TWO_XL",
                "optionType": "쭈리",
                "optionValue": "FALSE",
                "additionalFee": 0
            },
            "inventory": 500,
            "productStatus": "AVAILABLE"
        }
    ]
}
```
|Name|Type|Description|Constraint
|:----:|:----:|:---:|:--:|
|**id**|String|반려동물 종류|Not Null<br>현재 자유형식(변경 가능)<br>가이드라인 : 강아지, 고양이, ETC...|
|**originPrice**|String|반려동물 이름|Not Null<br>한/영 30자 이내 특수문자 불가능|
|**promotionType**|Integer|반려동물 나이|Not Null<br> 1 ~ 100 사이의 양의 정수|
|**promotionValue**|String|반려동물 성별|Not Null<br>`MALE` 또는 `FEMALE` 중 하나로 요청|
|**applied<br>PromotionPrice**|LocalDateTime|임시보호 시작일|Not Null<br>`yyyy-MM-dd` 형식 요청|

2023-09-07 13:30 UTC, EunChanNam requested changes
먼저 전체적으로 짚고 넘어갈 부분부터 리뷰할게요.
비즈니스 로직이 전부 application layer 로 넘어와 있어서 DDD 적이지 못한부분이 많아요.
예를 들면 applicaiton 에서 price 부분이나 promotion 같은 부분들은 전부 거의다? 비즈니스 로직으로 보이는데 비즈니스 로직은 domain layer 에서 처리하는게 좋은거같아요.

2023-09-07 14:14 UTC, EunChanNam requested changes
세부 리뷰 마쳤고, 
한가지 더 전체적으로 변수명에 대해서 얘기하고 싶은데
예를들어 Product Entity 안에서 사용하는 변수면 productCommonInfo 이런식으로 말고 commonInfo 이런식으로 가면 어떨까 싶어요. 
위는 한가지 예고 다른부분들도 이렇게 사용하시는 부분이 많더라고요. 
이부분은 어떻게 생각하시나요?

2023-09-07 14:20 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/application/price/ProductPriceService.java
> +    }
전부 팩토리 안의 로직에서 처리 가능할거같아요 불필요한 클래스로 보입니다

2023-09-07 14:21 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/application/price/promotion/ApplyPromotionFactory.java
> +    public PromotionPriceUtil calculateDiscountedAmount(
단순히  Calculator 를 리턴하는 로직인데 calculateDiscountedAmount 라는 이름은 부적합해보입니다.

2023-09-09 04:29 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
> +                .build();
좋은 의견입니다! 해당 부분 `ProductSingleSimpleResponse` 엔티티에 반영했습니다.

2023-09-09 04:40 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/dto/ProductOptionResponse.java
단일 변경 메소드 private `toSingleResponse`
실제 응답을 내리는 메소드 public `toResponse` 로 수정했습니다!

2023-09-09 05:09 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/Product.java
> +    private final List<ProductImage> images = new ArrayList<>();
`@OneToMany` 디폴트가 LAZY라는 건 예전에 JPA 강의 들을 때 배웠던 적이 있는데 까먹었던 내용이에요! OnDelete 옵션도 추가 완료했습니다!

2023-09-09 05:11 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/price/promotion/PromotionPriceUtil.java
> +    Integer getAppliedPromotionAmount(Integer originPrice, Promotion promotion);
메소드 자체가 할인을 적용하는 것이 아니라, `프로모션 할인액` 을 산정하는 로직이기 때문에 해당 가격으로 산정했습니다.

실제로 프로모션을 계산하는 로직은 (현 코드상에서) `productPriceService.applyPromotionDiscount` 함수가 별개로 존재합니다.

함수의 전체적인 명명을 다시 한번 고민해보고, 다음 PR에서 더 직관적인 내용으로 수정해보겠습니다!

2023-09-09 05:12 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/price/promotion/ApplyPromotionFactory.java
> +    public PromotionPriceUtil calculateDiscountedAmount(
좋습니다. 계산로직이 아니라 팩토리 로직임에도, calculate라는 이름이 붙는 것은 적절하지 않아 보여요!

2023-09-09 05:13 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/price/PromotionPriceUtil.java
앗 해당 코드는 패키징 과정에서 없어야 할 코드인데 명명이 같아 지워지지 않은 것 같습니다!
삭제할게요!

2023-09-13 19:04 UTC, merged