feat: Add BestProductSimple LookUp Api
TeamCommerce/backend-server pull request #86
Opened 2023-09-19 08:51 UTC by h-beeen

## Issue ticket link and number
- #85 

## Describe changes
- Best 상품 옵션을 위해 Best(String T/F) 옵션을 추가합니다.
추후 enum으로 바꿔볼까? 고민중입니다. mySQL의 boolean은 피하고 싶어요.
- `api/products/best` 엔드포인트가 추가됩니다.
해당 API는 호출시, best옵션이 T인 상품들을 기존 SImpleResponse 형태의 List로 반환됩니다.

- 예시 response

```json
[
    {
        "id": 1,
        "originPrice": 3000,
        "promotionType": "FIX_DISCOUNT",
        "promotionValue": 20,
        "finalPrice": 2980,
        "imgUrl": "naver.com",
        "colors": [
            "#FFFFFF",
            "#000000"
        ],
        "brand": "IUP_STUDIO",
        "name": "개좋은 아이템"
    },
    {
        "id": 2,
        "originPrice": 30000,
        "promotionType": "FIX_DISCOUNT",
        "promotionValue": 20,
        "finalPrice": 29980,
        "imgUrl": "asffsa",
        "colors": [],
        "brand": "IUP_STUDIO",
        "name": "개쩌는아이템"
    }
]
```

2023-09-19 09:29 UTC, EunChanNam requested changes
바뀔 부분이 조금 있는거같아요! 빠르게 수정하시고 커밋 푸쉬하시면 바로 다시 리뷰하러 올게요~ 
고생하셨어요 🫡

2023-09-19 09:29 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
> +                .orElseThrow(() -> CommerceException.of(PRODUCT_NOT_FOUND));
List 로 조회할 때는 `orElseThrow` 상황이 일어나지 않아서 해당 메소드에 `.orElseThrow` 부분은 없애면 될것같네요.

2023-09-19 09:29 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
> +    private String best;
베스트의 여부에 관한 속성으로 보이는데 `String` 보다는 `boolean` 관리하는게 어떨까요? 🤔

2023-09-19 09:29 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepository.java
> +    Optional<List<Product>> findBestProducts();
아하 여기가 Optional 이었군요! ㅋㅋ
컬렉션에 대한 조회에 결과가 없는 경우는 `empty List `가 반환되어서 `Optional` 처리 안하셔도 돼요!

2023-09-19 09:29 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
> +    public ResponseEntity<List<ProductSingleSimpleResponse>> findBestSimpleProducts() {
응답을 내보내는 부분! 저희 공통 `DTO` 를 사용해서 `Wrapper class` 사용하기로 한거 기억하실까요?!
제 `We share wish hair` 레포에 global/dto 에 `ResposneWrapper` 참고하시면 좋을거같아요!

2023-09-19 09:29 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/review/infra/ReviewQueryRepository.java
이 파일의 변경은 뭔지 알 수 있을까요? 실수겠죠??

2023-09-19 15:21 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
> +                .orElseThrow(() -> CommerceException.of(PRODUCT_NOT_FOUND));
맞아요! emptyList 상황을 가정했는데, 생각해보니까 emptyList는 null이 아니라 인식이 안되네요! 이 부분 다르게 예외 던지도록 수정하겠습니다!

2023-09-19 15:24 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
> +    private String best;
mySQL에서 boolean을 다루기 어렵기때문에, enum으로 처리하도록 하겠습니다!

2023-09-19 15:24 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
> +    public ResponseEntity<List<ProductSingleSimpleResponse>> findBestSimpleProducts() {
기억합니다! 이 부분도 적용해서 반영하겠습니다!

2023-09-19 15:25 UTC, h-beeen commented on src/main/java/com/commerce/backendserver/review/infra/ReviewQueryRepository.java
미사용 import가 머지 할 코드에 반영되었네요!
수정하겠습니다!

2023-09-19 16:34 UTC, h-beeen commented
이번에 PR 올린 부분만 Wrapper로 감싸서 진행해봤어요.
이 방식이 적절하게 적용된 코드라고 하면, 추후 PR에서 원래 코드까지 수정하도록 하겠습니다.

2023-09-20 02:49 UTC, EunChanNam approved these changes
하나 코멘트 드린거만 가볍게 적용하고 바로 머지해도 괜찮을거같네요!
고생하셨어요~ 👏

2023-09-20 02:49 UTC, EunChanNam commented on src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
> +    private void validateProducts(List<Product> products) {
메소드에서 **무엇을 검증** 하는지 명시하면 좋을거같아요.
예를 들면 `validateProductIsNotEmpty` 느낌으로 가면 어떨까요?

2023-09-20 16:50 UTC, merged